application: radius-levr
version: launchrock
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1m"

handlers:
- url: /
  script: landing.app
- url: /new
  script: newuser.app
- url: /music.*
  script: music.app
- url: /artist.*
  script: artist.app
- url: /signup
  script: signup.app
- url: /test.*
  script: test.app
- url: /feedback
  script: feedback.app
- url: /demo
  script: demo.app
- url: /shows.*
  script: shows.app


# namespace for contests
- url: /e.*
  script: contest.app
- url: /admin.*
  script: admin.app
  login: admin

#tasks and cronjobs
- url: /tasks.*
  script: tasks.app
  login: admin

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
  
- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: js
 
libraries:
- name: jinja2
  version: latest
