application: radius-levr
version: live2
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1m"

handlers:
- url: /
  script: landing.app
- url: /artist.*
  script: artist.app
- url: /signup
  script: signup.app
- url: /test
  script: test.app

#tasks and cronjobs
- url: /tasks.*
  script: tasks.app
  login: admin

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
  
- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: js
 
libraries:
- name: jinja2
  version: latest
  
