application: local-music
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1m"

handlers:
- url: /
  script: landing.app
  

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
  
- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: js
  
